<?php if ($this->pageCount): ?>

     <div >
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li>
                     <a  href="<?php echo $this->url($this->route, array('page' => $this->first), FALSE, TRUE); ?>?page=<?php echo $this->previous; ?>" class="pager">
                         <<
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <<
                     </a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a  href="<?php echo $this->url($this->route, array('page' => $this->first), FALSE, TRUE);?>?page=<?php echo $page; ?>" class="pager">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active">
                         <a href="#"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
                 <li>
                     <a  href="<?php echo $this->url($this->route, array('page' => $this->first), FALSE, TRUE); ?>?page=<?php echo $this->next; ?>" class="pager">
                         >>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         >>
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>

<script>

$(function(){
    $("a.pager").click(function(e){
        e.preventDefault() ;
              $.ajax({
        url: $(this).attr('href'),
        type: 'GET',
        success: function (data) {
     
    $('#myModal3').find('.modal-body').html(data);
                        $('#myModal3').modal({show:true});

            
        },
        error: function (xhr, status, error) {
            console.log('Error: ' + error.message);
        },
    });
    });
});

</script>

