
<?php
 $title = 'Add new Class';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('id','form');
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));

 ?>
<button type="button" id="addClassFormBtn" class="btn btn-info btn-sm" >Add </button><?php
echo $this->form()->closeTag();
    ?>
