<?php
 // module/Album/view/album/album/edit.phtml:
 $title = 'Edit Class';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form = $this->form;
 $form->setAttribute('id', 'editClassForm');
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 ?>
<button type="button" id="editClassFormBtn" class="btn btn-info btn-sm" >Edit </button><?php
  echo $this->form()->closeTag();
