
 <h1>Classes List</h1>

<p>
<button type="button" value="/gum/public//add"  class="btn btn-info btn-lg addClass" >Add new Class</button>
</p>
<!-- <p>
<button type="button"  class="btn btn-info btn-sm list" >Show</button>
</p> -->

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Edit</th>
     <th>Delete</th>
     <th>Show</th>

 </tr>
 <tbody class="tableContent"> </tbody>

</table>


<script>
$(function(){
  $("body").on("click","#editClassFormBtn",function(e){
    e.preventDefault();
    var name=JSON.stringify($("#editClassForm").serializeArray()[1].value);
    name = name.replace("\"", "");
    name = name.replace("\"", "");
        var id=JSON.stringify($("#editClassForm").serializeArray()[0].value);
        id = id.replace("\"", "");
        id = id.replace("\"", "");
  console.log(JSON.stringify($("#editClassForm").serializeArray()[1].value));
    $.ajax({
                     url:"/gum/public/album-rest/"+id,
                     type: 'PUT',

                     data: {'name':name},
                     success: function (data) {
                    //   $('#myModal3').modal('show')
                    //   $('.modal.in').removeClass('in');

                    //    console.log(JSON.stringify(data.data));
                      //  if(JSON.stringify(data.data)=="0"){
                          //alert("class exists");
                        // }
                        // else {
                        //
                        //   myFunction();
                        //
                        // }

                     },
                     error: function (e) {
                       myFunction();
                       $('.modal.in').removeClass('in');

                         console.log(e);

                     }

  });

  });


  $("body").on("click","#addClassFormBtn",function(e){
    e.preventDefault();
    var name=JSON.stringify($("#form").serializeArray()[1].value);
    name = name.replace("\"", "");
    name = name.replace("\"", "");

console.log(name);
  console.log(JSON.stringify($("#form").serializeArray()[1].value));
   $.ajax({
                     url:"/gum/public/album-rest",
                     type: 'POST',

                     data: {'name':name},
                     success: function (data) {
                    //   $('#myModal3').modal('show')
                    $('.modal.in').removeClass('in');

                        console.log(JSON.stringify(data.data));
                        if(JSON.stringify(data.data)=="0"){
                          //alert("class exists");
                          myFunction();
                        }
                        else {

                          myFunction();

                        }

                     },
                     error: function (e) {
                         console.log(e);

                     }

  });

  });




        $("body").on("click",'.deleteClass',function(){

          $.ajax({
                url: '/gum/public/album-rest/'+$(this).attr('value'),
                // dataType: "jsonp",
                type: 'DELETE',
                success: function (data) {
                  console.log(JSON.stringify(data));
                  alert((JSON.stringify(data)));
                  myFunction();

                },
                error: function (xhr, status, error) {
                    console.log('Error: ' + error.message);
                },
            });

        });
      //  $(".list").click(function(){
        $.ajax({
        url: '/gum/public/album-rest',
        // dataType: "jsonp",
        type: 'GET',
               dataType: "json",
        success: function (data) {
         data=JSON.stringify(data);
         var obj=JSON.parse(data);
         $(".tableContent").html('');
         for(var i=0; i<obj.data.length; i++){

           $(".tableContent").append("<tr><td>"+ obj.data[i].name +"</td><td><button class='btn btn-info btn-sm editClass' value="+obj.data[i].id+">Edit</button></td><td><button class='btn btn-info btn-sm btn-danger deleteClass' value="+obj.data[i].id+">Delete</button></td><td><button class='btn btn-info btn-sm showClass' value="+obj.data[i].id+">Show</button></td></tr>");

         }
            console.log("Data:"+((obj.data.length)));
            console.log("grtList");


        },
        error: function (xhr, status, error) {
            console.log('Error: ' + error.message);
        },
        });
    //    });


        function myFunction() {
          $.ajax({
          url: '/gum/public/album-rest',
          // dataType: "jsonp",
          type: 'GET',
                 dataType: "json",
          success: function (data) {
           data=JSON.stringify(data);
           var obj=JSON.parse(data);
           $(".tableContent").html('');
           for(var i=0; i<obj.data.length; i++){

             $(".tableContent").append("<tr><td>"+ obj.data[i].name +"</td><td><button class='btn btn-info btn-sm editClass' value="+obj.data[i].id+">Edit</button></td><td><button class='btn btn-info btn-sm deleteClass' value="+obj.data[i].id+">Delete</button></td><td><button class='btn btn-info btn-sm showClass' value="+obj.data[i].id+">Show</button></td></tr>");

           }
              console.log("Data:"+((obj.data.length)));
          },
          error: function (xhr, status, error) {
              console.log('Error: ' + error.message);
          },
          });



        }


        $("body").on("click",".editClass",function(){
        console.log("show button");
        if($("#myModal3").data('bs.modal') && $("#myModal3").data('bs.modal').isShown){
          // $('#myModal3').find('.modal-body').html("");
          $('.modal.in').removeClass("in");

          $('#myModal3').find('.modal-body').load('/gum/public//edit/'+$(this).attr('value'));
        }else{
        $('#myModal3').modal('show').find('.modal-body').load('/gum/public//edit/'+$(this).attr('value'));
        }


        });


      $("body").on("click",".showClass",function(){
      console.log("show button");
      if($("#myModal3").data('bs.modal') && $("#myModal3").data('bs.modal').isShown){
        // $('#myModal3').find('.modal-body').html("");
        $('.modal.in').removeClass("in");

        $('#myModal3').find('.modal-body').load('/gum/public//show/'+$(this).attr('value'));
      }else{
      $('#myModal3').modal('show').find('.modal-body').load('/gum/public//show/'+$(this).attr('value'));
      }


      });


      $(".addClass").on("click",function(e){

      e.preventDefault();
      console.log("add class");
      if($("#myModal3").data('bs.modal') && $("#myModal3").data('bs.modal').isShown){
        $('.modal.in').removeClass("in");

        $('#myModal3').find('.modal-body').load($(this).attr('value'));
      }else{
        $('#myModal3').modal('show').find('.modal-body').load($(this).attr('value'));

      }


      });


});

</script>

<div id="myModal3" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">


      </div>
      <div class="modal-footer">
        <button id="closeModal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
