<div class="container-fluid">
<div class="jumbotron jumbotron-fluid">
  <div >
    <h1 class="display-3">Login Here !</h1>
  </div>
</div>

 <?php
 $form->setAttribute('id','userForm');
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 ?>
 <div class="form-group">
   <?php
   echo $this->formRow($form->get('username')->setAttribute('class','form-control'));
   ?>
 </div>
 <?php
 ?>
 <div class="form-group">
   <?php
   echo $this->formRow($form->get('password')->setAttribute('class','form-control')->setAttribute('type','password'));
   ?>
 </div>
 <?php
 ?>
<button type="button" id="addUserFormBtn" class="btn btn-info btn-sm" >Login </button><?php
echo $this->form()->closeTag();
    ?>

<script>

$(function(){
  $('#addUserFormBtn').click(function(){
    var username=JSON.stringify($("#userForm").serializeArray()[1].value);
    username = username.replace("\"", "");
    username = username.replace("\"", "");
    var password=JSON.stringify($("#userForm").serializeArray()[2].value);
    password = password.replace("\"", "");
    password = password.replace("\"", "");
    console.log(username+password);
    $.ajax({
      url: '/gum/public//login',
      type: 'POST',
      data: {
        'username': username,
        'password': password,
      },
      success: function (data) {
        console.log("Data:"+JSON.stringify(data.data));

        if(JSON.stringify(data.data)=="1"){
        //  header('Location: https://www.google.com');
        $.cookie('loggedin','true');
        window.location = "/gum/public";
        }
        else {
          alert("Invalid username or password");
        }
      },
      error: function (xhr, status, error) {
          console.log('Error: ' + error.message);
      },
    });
  });
});
</script>
