<h1>Students List</h1>
<p>
  <button type="button" class="btn btn-info btn-lg addStudent" >Add new Student</button>
</p>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <tbody class="studentTableContent"> </tbody>
</table>
<nav aria-label="...">
  <ul class="paginationStudent">
  </ul>
</nav>
<style>
.paginationStudent {
    display: inline-block;
}
.paginationStudent a {
    color: black;
    float: left;
    padding: 8px 16px;
    text-decoration: none;
}

.paginationStudent a.active {
    background-color: #2AABD2;
    color: white;
    border-radius: 5px;
}

.paginationStudent a:hover:not(.active) {
    background-color: #ddd;
    border-radius: 5px;
}
</style>

<script>

$(function(){

    var variableId =<?php echo $id; ?>;// variable to retrieve the id of class
    console.log(variableId);

    //Function for displaying the list of students
    myFunction2(0);

    //Edit button in Edit 2 form for editing student
    $("body").on("click","#editStudentFormBtn",function(e){
    e.preventDefault();
    e.stopImmediatePropagation();
    console.log(JSON.stringify($("#editStudentForm").serializeArray()));
    var name=JSON.stringify($("#editStudentForm").serializeArray()[3].value);
    name = name.replace("\"", "");
    name = name.replace("\"", "");
    var email=JSON.stringify($("#editStudentForm").serializeArray()[4].value);
    email = email.replace("\"", "");
    email = email.replace("\"", "");
    var id=JSON.stringify($("#editStudentForm").serializeArray()[0].value);
    id = id.replace("\"", "");
    id = id.replace("\"", "");
    var pid=JSON.stringify($("#editStudentForm").serializeArray()[1].value);
    pid = pid.replace("\"", "");
    pid = pid.replace("\"", "");
    console.log(name+email+id);
    $.ajax({
      url:"/gum/public/student-rest/"+id,
      type: 'PUT',
      data: {
        'id':id,
        'name': name,
        'email': email,
        'classs': '',
        'pid':pid,
      },
      success: function (data) {
        if(data.data=='0'){
          alert('Invalid Email !');
        }
        else {
          $("#myModal3").find(".modal-body").html(data.data);
          console.log((data));
        }
      },
      error: function (e) {
        console.log(e);
      }
    });
  });


    //add button in show phtml for modal adding student
    $(".addStudent").one("click",function(e){
    e.preventDefault();
    console.log("add student");
    $('#myModal3').modal('show').find('.modal-body').load('/gum/public//add2/'+variableId);


    //add button in add 2 form for adding student
    $("body").on("click","#addStudentFormBtn",function(e){
      e.preventDefault();
      e.stopImmediatePropagation();
      var name=JSON.stringify($("#addStudentFormId").serializeArray()[2].value);
      name = name.replace("\"", "");
      name = name.replace("\"", "");
      var email=JSON.stringify($("#addStudentFormId").serializeArray()[4].value);
      email = email.replace("\"", "");
      email = email.replace("\"", "");
      var pid=JSON.stringify($("#addStudentFormId").serializeArray()[1].value);
      pid = pid.replace("\"", "");
      pid = pid.replace("\"", "");
      console.log(name);
      console.log(JSON.stringify($("#addStudentFormId").serializeArray()));
      $.ajax({
        url:"/gum/public/student-rest",
        type: 'POST',
        data: {
          'id':'',
          'pid':pid,
          'classs':'',
          'name':name,
          'email':email,
        },
        success: function (data) {
          if(data.data=='0'){
            alert("Invalid Email !");
          }
          else{
            $("#myModal3").find(".modal-body").html(data.data);
            console.log(JSON.stringify(data.data));
          }
        },
        error: function (e) {
          console.log(e);
        }
      });
    });
  });

  //pagination
  $("body").on('click','.studentPageLink',function(e){
    e.preventDefault();
    e.stopImmediatePropagation();
    studentPageValue=$(this).attr('value');
    console.log(studentPageValue);
    myFunction2(studentPageValue);
  });
  //edit student in show phtml
  $("body").on("click",'.editStudent',function(e){
    e.stopImmediatePropagation();
    console.log("edit student");
    $('#myModal3').modal('show').find('.modal-body').load('/gum/public//edit2/'+$(this).attr('value'));
  });
  //delete student in show phtml
  $("body").on("click",'.deleteStudent',function(e){
    e.stopImmediatePropagation();
    console.log("studentDelete");
    $.ajax({
      url: '/gum/public/student-rest/'+$(this).attr('value'),
      type: 'DELETE',
      success: function (data) {
        console.log(JSON.stringify(data));
        $("#myModal3").find(".modal-body").html(data.data);
      },
      error: function (xhr, status, error) {
        console.log('Error: ' + error.message);
      },
    });
  });
var obj;
var totalStudentRecords;

  // Function for displaying students
  function myFunction2(studentPageValue){

    $.ajax({
    url: '/gum/public/student-rest/'+variableId,
    type: 'GET',
    data: {
      'page': studentPageValue*5,
      'limit': 5
    },
    success: function (data) {
      //for getting all the students of a particular paginator
      dataStudent=JSON.stringify(data.data[0]);
      console.log(data.data[0].length);
      obj=JSON.parse(dataStudent);//got all students in array

      //for total number of students of particular class
      totalStudentRecords=JSON.stringify(data.data[1]);
      totalStudentRecords=JSON.parse(totalStudentRecords);
      totalStudentRecords=totalStudentRecords[0].num;//got them as integer
      console.log(totalStudentRecords);
      var totalStudentPages=Math.ceil(totalStudentRecords/5);
      $(".paginationStudent").html('');
      $(".studentTableContent").html('');

      //loop-pagination for students
      for(var j = 1 ; j <= totalStudentPages ; j++){
        if((j-1)==studentPageValue)
          $(".paginationStudent").append("<li class='page-item'><a class='page-link active studentPageLink' value="+(j-1)+">"+j+"</a></li>")
        else {
          $(".paginationStudent").append("<li class='page-item'><a class='page-link studentPageLink' value="+(j-1)+">"+j+"</a></li>")

        }
      }

      //loop for displaying students
      for(var i=0; i<data.data[0].length; i++){
        $(".studentTableContent").append("<tr><td>"+ obj[i].name +"</td><td>"+ obj[i].email +"</td><td><button class='btn btn-info btn-sm editStudent' value="+obj[i].id+">Edit</button></td><td><button class='btn btn-info btn-sm btn-danger deleteStudent' value="+obj[i].id+">Delete</button></td></tr>");
      }
      console.log("grtstuList");

    },
    error: function (xhr, status, error) {
        console.log('Error: ' + error.message);
    },
  });
  }

});

</script>
